baseURL: https://agrocompostela.com
enableRobotsTXT: true
Paginate: 12
params:
  title: Agrocompostela
  titleSeparator: ·
  image: uploads/logo.png
  org:
    name: Agrocompostela CA
    email: ntrrgx@gmail.com
    logo: uploads/logo.png
    isologo: uploads/isologo.png
    social:
      facebook:
        url: https://www.facebook.com/agrocompostela
        icon: social-facebook.svg
        text: Agrocompostela
      twitter:
        url: https://twitter.com/agrocompostela
        icon: social-twitter.svg
        text: "@agrocompostela"
      instagram:
        url: https://www.instagram.com/agrocompostela
        icon: social-instagram.svg
        text: "@agrocompostela"
      linkedin:
        url: https://www.linkedin.com/in/agrocompostela
        icon: social-linkedin.svg
        text: Agrocompostela
      youtube:
        url: https://www.youtube.com/channel/asd_sdqwdkjlaxnajd
        icon: social-youtube.svg
        text: Agrocompostela
      telegram:
        url: https://t.me/agrocompostela
        icon: social-telegram.svg
        text: "@agrocompostela"
      email:
        url: mailto://info@agrocompostela.com
        icon: social-email.svg
        text: info@agrocompostela.com
      phone:
        url: tel://580001234567
        icon: social-phone.svg
        text: +58 XXX-1234567
  currencies:
    - USD
    - VES
defaultContentLanguage: es
defaultContentLanguageInSubdir: true
languages:
  en:
    languageName: English
    params:
      description: A small description of the organization
      currency: USD
      deals:
        - flour-1kg
        - extract-1kg
  es:
    languageName: Español
    params:
      description: Una pequeña descripción de la organización
      currency: VES
      deals:
        - flour-1kg
        - extract-1kg

