[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.50"

[context.deploy-preview]
  command = "hugo -DEF --baseURL=/"

[[headers]]
  for = "/*"

[headers.values]
  X-Frame-Options = "SAMEORIGIN"
  X-XSS-Protection = "1; mode=block"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "origin-when-cross-origin"

[[redirects]]
  from = "/en/*"
  to = "/en/404/"
  status = 404

[[redirects]]
  from = "/es/*"
  to = "/es/404/"
  status = 404

