---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/blog
  label: Articles
  create: all
  match: "**/*"
  exclude: "**/_*"
- type: directory
  path: content/recipes
  label: Recipes
  create: all
  match: "**/*"
- type: directory
  path: content/products
  label: Shop
  create: all
  match: "**/*"
  exclude: "**/_*"
- type: heading
  label: Data
- type: document
  path: config.yaml
  label: Parameters
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.49.2
