---
label: Products
hide_body: false
is_partial: false
fields:
- type: text
  label: Title
  name: title
  config:
    required: true
- type: datetime
  label: Date
  name: date
  config:
    date_format: YYYY/MM/DD
- type: text
  name: description
  label: Description
- type: file
  name: image
  label: Thumbnail
- type: image_gallery
  label: Images
  name: images
  description: This images will be dsplayed at the product page
- type: tag_list
  label: Tags
  name: tags
- type: boolean
  name: draft
  label: Draft
